// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kuliah.Data;

#nullable disable

namespace kuliah.Migrations
{
    [DbContext(typeof(kuliahContext))]
    [Migration("20240305062015_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("kuliah.Models.Dosen", b =>
                {
                    b.Property<int>("Nip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Nip"));

                    b.Property<string>("Nama_Dosen")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Nip");

                    b.ToTable("Dosen");
                });

            modelBuilder.Entity("kuliah.Models.Mahasiswa", b =>
                {
                    b.Property<int>("Nim")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Nim"));

                    b.Property<string>("Alamat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jenis_Kelamin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nama_Msh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tgl_Lahir")
                        .HasColumnType("datetime2");

                    b.HasKey("Nim");

                    b.ToTable("Mahasiswa");
                });

            modelBuilder.Entity("kuliah.Models.Marakuliah", b =>
                {
                    b.Property<int>("Kode_MK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Kode_MK"));

                    b.Property<string>("Nama_MK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Kode_MK");

                    b.ToTable("Marakuliah");
                });

            modelBuilder.Entity("kuliah.Models.Perkuliahan", b =>
                {
                    b.Property<int>("Nim")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Nim"));

                    b.Property<int>("Kode_MK")
                        .HasColumnType("int");

                    b.Property<string>("Nilai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nip")
                        .HasColumnType("int");

                    b.HasKey("Nim");

                    b.ToTable("Perkuliahan");
                });
#pragma warning restore 612, 618
        }
    }
}
